export type {
  AttachmentId,
  AttachmentMetadata,
  CapabilityAccess,
  CreateMetadataInput,
  DocumentId,
  DocumentMetadata,
  DocumentRevision,
  KnownLifecycleState,
  LifecycleState,
  MetadataPatch,
  PersonId,
  PersonReference,
  RelatedDocumentReference,
  Sensitivity,
  SharingPolicy,
  Visibility,
} from "./domain/document.ts";
export {
  assignRfcNumber,
  attachmentId,
  createDocumentMetadata,
  documentId,
  documentRevision,
  DomainError,
  knownLifecycleStates,
  markDeleted,
  markPublished,
  markUnpublished,
  nextDocumentRevision,
  personId,
  requireRevision,
  updateDocumentMetadata,
  updateSharingPolicy,
  validatePerson,
} from "./domain/document.ts";
export type {
  CommentActor,
  CommentAnchor,
  CommentMessage,
  CommentMessageId,
  CommentState,
  CommentThread,
  CommentThreadId,
  CreateThreadInput,
} from "./domain/comments.ts";
export {
  commentMessageId,
  commentThreadId,
  createCommentThread,
  deleteCommentMessage,
  deleteCommentThread,
  editCommentMessage,
  emptyCommentState,
  replaceCommentAnchor,
  replyToCommentThread,
  setCommentThreadResolution,
} from "./domain/comments.ts";
export type {
  DocumentAction,
  Principal,
  WorkspaceAction,
  WorkspaceRole,
} from "./domain/authorization.ts";
export {
  authorizeDocument,
  AuthorizationError,
  authorizeWorkspace,
  documentActions,
  isAdministrator,
  isDocumentActionAllowed,
} from "./domain/authorization.ts";
export type {
  ApiKeyRecord,
  AuthenticationState,
  CreatedApiKey,
  CreatedSession,
  SessionRecord,
  WorkspaceIdentity,
} from "./domain/authentication.ts";
export {
  authenticateApiKey,
  authenticateSession,
  AuthenticationError,
  createApiKey,
  createWorkspaceSession,
  emptyAuthenticationState,
  loginOwner,
  logoutSession,
  revokeApiKey,
  setupOwner,
} from "./domain/authentication.ts";
export type { LineRange, TextReplacement } from "./domain/body.ts";
export { applyUniqueTextReplacements, BodyEditError, readLineRange } from "./domain/body.ts";
export type {
  CatalogSearchOptions,
  CatalogSummary,
  DocumentReservation,
  PeopleDirectoryEntry,
  RfcAllocation,
  RegistryEntry,
  RegistryStatus,
  WorkspaceCatalogState,
} from "./domain/catalog.ts";
export {
  activateDocument,
  allocateRfcNumber,
  applyCatalogSummary,
  emptyWorkspaceCatalog,
  findPerson,
  normalizeSearchText,
  publicCatalog,
  reserveDocument,
  searchCatalog,
  tombstoneDocument,
  upsertPerson,
} from "./domain/catalog.ts";
export { encodeBase62, taggedId } from "./application/identifiers.ts";
export type {
  DigestService,
  DurableDocumentJournalService,
  IdGeneratorService,
  JournalEntry,
  JournalEntryInput,
  JournalEntryKind,
  ObjectStoreService,
  PutObjectOptions,
  SecretHasherService,
  SecureTokenService,
  StoredObject,
  WorkspaceStateStoreService,
} from "./application/ports.ts";
export {
  Digest,
  DurableDocumentJournal,
  IdGenerator,
  ObjectStore,
  SecretHasher,
  SecureToken,
  StorageError,
  WorkspaceStateStore,
} from "./application/ports.ts";
